import React from 'react';
import {Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

export type VisualBeat = { visual:string; text:string; seconds:number; emphasis?:string; assetSrc?:string; label?:string; value?:number; unit?:string; sources?:string[]; mode?:string };

const Glass:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:'rgba(10,15,22,.72)',border:'1px solid rgba(255,255,255,.12)',boxShadow:'0 30px 80px rgba(0,0,0,.35)',borderRadius:18,backdropFilter:'blur(12px)',...style}}>{children}</div>;
const SourceFooter:React.FC<{sources?:string[]}>=({sources})=>{if(!sources?.length)return null;const text=sources.length===1?sources[0]:`${sources[0]} + ${sources.length-1} more source${sources.length>2?'s':''}`;return <div style={{position:'absolute',left:80,right:80,bottom:52,fontSize:17,color:'rgba(255,255,255,.42)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>SOURCE · {text}</div>};
const MotionShell:React.FC<{children:React.ReactNode;mode?:string}>=({children,mode='hold'})=>{const frame=useCurrentFrame();const{fps}=useVideoConfig();const enter=spring({frame,fps,config:{damping:22,stiffness:110,mass:.65}});const y=interpolate(enter,[0,1],[28,0]);const scale=mode==='punch'?interpolate(frame,[0,45],[1,1.035],{extrapolateRight:'clamp'}):1;const opacity=interpolate(enter,[0,1],[0,1]);return <div style={{width:'100%',height:'100%',display:'flex',alignItems:'center',justifyContent:'center',opacity,transform:`translateY(${y}px) scale(${scale})`}}>{children}</div>};

export const StatVisual:React.FC<VisualBeat>=({text,value=94,unit='%',sources,label='KEY FIGURE',mode})=>{const frame=useCurrentFrame();const{fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:180,stiffness:80}});const n=Math.round(interpolate(p,[0,1],[0,value]));const progress=unit==='%'?Math.min(100,n):Math.min(100,n*10);return <MotionShell mode={mode}><Glass style={{padding:52,width:760,position:'relative'}}><div style={{fontSize:20,letterSpacing:5,opacity:.42,marginBottom:12}}>{label}</div><div style={{fontSize:118,fontWeight:850,letterSpacing:-7}}>{n}<span style={{fontSize:54,marginLeft:10,opacity:.65}}>{unit}</span></div><div style={{height:8,background:'rgba(255,255,255,.1)',margin:'30px 0',borderRadius:8}}><div style={{height:'100%',width:`${progress}%`,background:'white',borderRadius:8}}/></div><div style={{fontSize:28,lineHeight:1.25,color:'rgba(255,255,255,.76)'}}>{text}</div><SourceFooter sources={sources}/></Glass></MotionShell>};
export const ClaimVisual:React.FC<VisualBeat>=({text,sources,mode})=>{const frame=useCurrentFrame();return <MotionShell mode={mode}><Glass style={{padding:65,width:1320,position:'relative'}}><div style={{fontSize:24,letterSpacing:6,opacity:.45,marginBottom:28}}>THE CLAIM</div><div style={{width:90,height:5,background:'white',marginBottom:30,transformOrigin:'left',transform:`scaleX(${Math.min(1,frame/24)})`}}/><div style={{fontSize:62,lineHeight:1.08,fontWeight:720,maxWidth:1180}}>{text}</div><SourceFooter sources={sources}/></Glass></MotionShell>};
export const TimelineVisual:React.FC<VisualBeat>=({text,sources,mode})=><MotionShell mode={mode}><Glass style={{padding:50,width:1320,position:'relative'}}><div style={{fontSize:25,letterSpacing:6,opacity:.55,marginBottom:34}}>THE TIMELINE</div><div style={{position:'relative',height:110}}><div style={{position:'absolute',left:0,right:0,top:42,height:4,background:'rgba(255,255,255,.25)'}}/>{[0,1,2,3,4].map(i=><div key={i} style={{position:'absolute',left:`${i*25}%`,top:23,width:42,height:42,borderRadius:'50%',background:'white',boxShadow:'0 0 0 8px rgba(255,255,255,.08)'}}/>)}</div><div style={{fontSize:34,lineHeight:1.25,maxWidth:1100}}>{text}</div><SourceFooter sources={sources}/></Glass></MotionShell>;
export const MapVisual:React.FC<VisualBeat>=({text,sources,mode})=>{const frame=useCurrentFrame();const drift=interpolate(frame,[0,180],[0,-40],{extrapolateRight:'clamp'});return <MotionShell mode={mode}><Glass style={{padding:35,width:1360,height:600,overflow:'hidden',position:'relative'}}><div style={{position:'absolute',inset:-100,transform:`translateX(${drift}px)`,opacity:.9,backgroundImage:'radial-gradient(circle,rgba(255,255,255,.32) 1px,transparent 1px)',backgroundSize:'34px 34px'}}/><div style={{position:'absolute',left:220,top:150,width:900,height:3,background:'rgba(255,255,255,.18)',transform:'rotate(-8deg)'}}/>{[[280,150],[650,275],[1010,180],[830,440]].map(([x,y],i)=><div key={i} style={{position:'absolute',left:x,top:y,width:24,height:24,borderRadius:'50%',background:'white',boxShadow:'0 0 0 14px rgba(255,255,255,.09)'}}/>)}<div style={{position:'absolute',left:60,bottom:45,fontSize:31,maxWidth:950}}>{text}</div><SourceFooter sources={sources}/></Glass></MotionShell>};
export const QuoteVisual:React.FC<VisualBeat>=({text,sources,mode})=><MotionShell mode={mode}><Glass style={{padding:65,width:1320,borderLeft:'5px solid white',position:'relative'}}><div style={{fontSize:80,lineHeight:.8,opacity:.35}}>“</div><div style={{fontSize:55,lineHeight:1.12,fontWeight:650,maxWidth:1180}}>{text}</div><SourceFooter sources={sources}/></Glass></MotionShell>;
export const AssetVisual:React.FC<VisualBeat>=({text,assetSrc,sources,mode})=>{const frame=useCurrentFrame();const scale=interpolate(frame,[0,180],[1,1.08],{extrapolateRight:'clamp'});const drift=interpolate(frame,[0,180],[0,-18],{extrapolateRight:'clamp'});const src=assetSrc?(assetSrc.startsWith('http://')||assetSrc.startsWith('https://')?assetSrc:staticFile(assetSrc.replace(/^\//,''))):undefined;return <div style={{position:'relative',width:'100%',height:'100%',overflow:'hidden'}}>{src?<Img src={src} style={{width:'100%',height:'100%',objectFit:'cover',transform:`translateX(${mode==='move'?drift:0}px) scale(${scale})`,filter:'brightness(.55) saturate(.8)'}}/>:<div style={{position:'absolute',inset:0,background:'linear-gradient(135deg,#101923,#2c3948)'}}/>}<div style={{position:'absolute',inset:0,background:'linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.08))'}}/><MotionShell mode={mode}><div style={{position:'absolute',left:120,bottom:110,maxWidth:1100,fontSize:58,fontWeight:750,lineHeight:1.08}}>{text}</div></MotionShell><SourceFooter sources={sources}/></div>};
export const Visual:React.FC<VisualBeat>=props=>{switch(props.visual){case'stat':case'counter':return <StatVisual {...props}/>;case'timeline':return <TimelineVisual {...props}/>;case'map':return <MapVisual {...props}/>;case'quote':return <QuoteVisual {...props}/>;case'claim':case'text':return <ClaimVisual {...props}/>;case'broll':case'image':case'portrait':case'logo':return <AssetVisual {...props}/>;default:return <AssetVisual {...props}/>}};
